org: jfbcable
app: myapp
service: dazzler-web-push

provider:
  name: aws
  runtime: nodejs8.10
  stage: test
  region: eu-west-1
  environment:
    DOMAIN: https://remittir.com/ # no need to change this domain for testing it
    VAPID_PUBLIC_KEY: BLpTsaEAy-BGQnkZ1DeFYYNS6EH1gWP-cP49n9NmbWtjkSVMJQjj-wVI0tapfsK7Ju9r0VQz7jpE9kf8BETAdns
    VAPID_PRIVATE_KEY: LtWhacMtRs63fhABUUMLOynMRTKTffIf7oQuRpwChFc
    APPW_ROLE: arn:aws:iam::746161738563:role/client-access-appw-cd-live
    STATE_BUCKET: dazzler-test-meta
    LANG: mr

functions:
  vapidPublicKey:
    handler: handler.vapidPublicKey
    events: 
      - http:
          path: vapidPublicKey
          method: get

  sendNotification:
    handler: handler.sendNotification
    events: 
      - http:
          path: sendNotification
          method: post

  registerOrSendToAll:
    handler: handler.registerOrSendToAll
    events: 
      - http:
          path: register
          method: post
      - http:
          path: sendToAll
          method: post

  notifyNewOrChanged:
    handler: handler.notifyNewOrChanged
    events: 
      - sns: arn:aws:sns:eu-west-1:576677253489:test-ws-appw-merge-isite-OutputTopic-TU2HACJ25UGS

  statics:
    handler: handler.statics
    events: 
      - http:
          path: index.html
          method: get
      - http:
          path: index.js
          method: get
      - http:
          path: service-worker.js
          method: get

