AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: publish media files
Resources:
  dazzlerWebpush:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      InlineCode: 'exports.handler = function(event,context){}'
      Description: notify Dazzler edit of new clips and episodes
      FunctionName: 
        'Fn::Join':
          - '-'
          - - dazzler-web-push
            - !Ref Environment
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: !ImportValue
              'Fn::Join':
                - '-'
                - - !Ref Environment
                  - mesh2topic
                  - GoodUploadTopic
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          VAPID_PUBLIC_KEY: !Ref VapidPublicKey
          VAPID_PRIVATE_KEY: !Ref VapidPrivateKey
          LANGUAGES: !Ref Languages
          APPW_ROLE: !Ref APPWRole
          STATE_BUCKET: !FindInMap 
            - OperationsMap
            - BucketMap
            - !Ref Environment
          APPW_EXTENSION_BUCKET: !FindInMap 
            - OperationsMap
            - AppwExtensionMap
            - !Ref Environment
      Policies:
        - Statement:
            - Action: 'sts:AssumeRole'
              Effect: Allow
              Resource: !FindInMap 
                - OperationsMap
                - AppwMap
                - !Ref Environment
        - S3ReadPolicy:
            BucketName: !FindInMap 
              - OperationsMap
              - BucketMap
              - !Ref Environment
        - S3ReadPolicy:
            BucketName: !FindInMap 
              - OperationsMap
              - AppwExtensionMap
              - !Ref Environment
  AliasForLambda:
    Type: 'AWS::Lambda::Alias'
    Properties:
      FunctionVersion: $LATEST
      FunctionName: !Ref dazzlerWebpush
      Name: !Ref Environment
Parameters:
  Environment:
    Default: test
    Type: String
    ConstraintDescription: must be test or live
    Description: The deployment environment
    AllowedValues:
      - live
      - test
  APPWRole:
    Default: arn:aws:iam::746161738563:role/client-access-appw-cd-live
    Type: String
  VapidPublicKey:
    Description: notifications public key
    Type: String
    Default: BLpTsaEAy-BGQnkZ1DeFYYNS6EH1gWP-cP49n9NmbWtjkSVMJQjj-wVI0tapfsK7Ju9r0VQz7jpE9kf8BETAdns
  VapidPrivateKey:
    Description: notifications private key
    Type: String
    Default: LtWhacMtRs63fhABUUMLOynMRTKTffIf7oQuRpwChFc
  Languages:
    Description: list of two letter language codes e.g. mr for Marathi
    Type: String
    Default: mr
  LambdaTimeout:
    Default: '30'
    Type: Number
    Description: >-
      The function execution time (in seconds) after which Lambda terminates the
      function. 
  LambdaMemorySize:
    Default: '128'
    Type: Number
    Description: 'The amount of memory, in MB, that is allocated to your Lambda function.'
Mappings:
  OperationsMap:
    BucketMap:
      test: dazzler-test-meta
      live: dazzler-meta
    AppwExtensionMap:
      test: ws-partners-appw-merge-test
      live: ws-partners-appw-merge
