AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: publish media files
Resources:
  dazzlerWebpush:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      InlineCode: 'exports.handler = function(event,context){}'
      Description: notify Dazzler edit of new clips and episodes
      FunctionName: 
        'Fn::Join':
          - '-'
          - - dazzler-web-push
            - !Ref Environment
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: !FindInMap
              - OperationsMap
              - TopicMap
              - !Ref Environment
      Environment:
        Variables:
          DOMAIN: !Ref Domain
          VAPID_PUBLIC_KEY: !Ref VapidPublicKey
          VAPID_PRIVATE_KEY: !Ref VapidPrivateKey
          APPW_ROLE: !Ref APPWRole
          STATE_BUCKET: !FindInMap 
            - OperationsMap
            - BucketMap
            - !Ref Environment
          APPW_EXTENSION_BUCKET: !FindInMap 
            - OperationsMap
            - AppwExtensionMap
            - !Ref Environment
      Policies:
        - Statement:
            - Action: 'sts:AssumeRole'
              Effect: Allow
              Resource: !Ref APPWRole
        - S3ReadPolicy:
            BucketName: !FindInMap 
              - OperationsMap
              - BucketMap
              - !Ref Environment
        - S3ReadPolicy:
            BucketName: !FindInMap 
              - OperationsMap
              - AppwExtensionMap
              - !Ref Environment
  AliasForLambda:
    Type: 'AWS::Lambda::Alias'
    Properties:
      FunctionVersion: $LATEST
      FunctionName: !Ref dazzlerWebpush
      Name: !Ref Environment
Parameters:
  Environment:
    Default: test
    Type: String
    ConstraintDescription: must be test or live
    Description: The deployment environment
    AllowedValues:
      - live
      - test
  APPWRole:
    Default: arn:aws:iam::746161738563:role/client-access-appw-cd-live
    Type: String
  Domain:
    Description: needed by VAPID
    Type: String
    Default: bbc.com
  VapidPublicKey:
    Description: notifications public key
    Type: String
    Default: BLpTsaEAy-BGQnkZ1DeFYYNS6EH1gWP-cP49n9NmbWtjkSVMJQjj-wVI0tapfsK7Ju9r0VQz7jpE9kf8BETAdns
  VapidPrivateKey:
    Description: notifications private key
    Type: String
    Default: LtWhacMtRs63fhABUUMLOynMRTKTffIf7oQuRpwChFc
  LambdaTimeout:
    Default: '30'
    Type: Number
    Description: >-
      The function execution time (in seconds) after which Lambda terminates the
      function. 
  LambdaMemorySize:
    Default: '128'
    Type: Number
    Description: 'The amount of memory, in MB, that is allocated to your Lambda function.'
Mappings:
  OperationsMap:
    BucketMap:
      test: ws-dazzler-assets-test
      live: ws-dazzler-assets
    AppwExtensionMap:
      test: ws-partners-appw-merge-test
      live: ws-partners-appw-merge
    TopicMap:
      test: arn:aws:sns:eu-west-1:576677253489:test-ws-appw-merge-isite-OutputTopic-TU2HACJ25UGS
      live: TBD
